<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>HIPAA Notice of Privacy Practices | KarmaTMS</title>
    <meta name="description"
        content="Notice of Privacy Practices - Learn how KarmaTMS protects your health information and your rights under HIPAA.">

    <?php include 'includes/header-links.php'; ?>
</head>

<body>
    <?php include 'includes/header.php'; ?>

    <!-- Hero Section -->
    <section class="pt-32 pb-20"
        style="background: linear-gradient(to bottom right, rgba(87, 38, 112, 0.05), rgba(168, 85, 247, 0.1));">
        <div class="container mx-auto px-4">
            <div class="text-center max-w-4xl mx-auto">
                <span class="inline-block px-4 py-2 rounded-full mb-4 text-sm font-bold"
                    style="background-color: rgba(87, 38, 112, 0.1); color: #572670; border: 1px solid rgba(87, 38, 112, 0.2);">
                    HIPAA Privacy Notice
                </span>
                <h1 class="text-4xl md:text-5xl lg:text-6xl font-bold text-gray-900 leading-tight mb-6">
                    Notice of
                    <span class="block text-transparent bg-clip-text"
                        style="background: linear-gradient(to right, #572670, #a855f7); -webkit-background-clip: text; background-clip: text; -webkit-text-fill-color: transparent;">
                        Privacy Practices
                    </span>
                </h1>
                <p class="text-xl text-gray-600 leading-relaxed mb-8">
                    This notice describes how medical information about you may be used and disclosed
                    and how you can access this information. Please review it carefully and keep a copy for your
                    records.
                </p>
                <div class="flex items-center justify-center gap-6 text-sm text-gray-500 mb-8">
                    <div class="flex items-center gap-2">
                        <i data-lucide="clock" class="w-4 h-4"></i>
                        <span>Effective: March 1, 2024</span>
                    </div>
                    <div class="flex items-center gap-2">
                        <i data-lucide="shield" class="w-4 h-4"></i>
                        <span>HIPAA Compliant</span>
                    </div>
                </div>
                <div class="flex flex-wrap justify-center gap-4">
                    <a href="tel:7607605675" class="bm-outline-btn" style="border-color: #572670; color: #572670;">
                        <i data-lucide="phone" class="w-5 h-5 mr-2"></i>
                        Questions: 760-760-5675
                    </a>
                </div>
            </div>
        </div>
    </section>

    <!-- Our Commitment Section -->
    <section class="py-20 bg-white">
        <div class="container mx-auto px-4">
            <div class="text-center mb-16">
                <h2 class="text-3xl lg:text-4xl font-bold text-gray-900 mb-6">
                    Our <span style="color: #572670;">Privacy Commitment</span>
                </h2>
                <p class="text-xl text-gray-600 max-w-3xl mx-auto">
                    We are committed to protecting the privacy of your health information and
                    using it only as necessary to provide quality healthcare services.
                </p>
            </div>

            <div class="max-w-4xl mx-auto">
                <div class="bm-benefit-card p-8">
                    <div class="flex items-start gap-6">
                        <div class="w-16 h-16 rounded-xl flex items-center justify-center flex-shrink-0"
                            style="background: linear-gradient(to bottom right, #572670, #a855f7);">
                            <i data-lucide="shield" class="w-8 h-8 text-white"></i>
                        </div>
                        <div>
                            <h3 class="text-2xl font-bold text-gray-900 mb-4">Protected Health Information (PHI)</h3>
                            <p class="text-gray-600 mb-6">
                                This notice applies to all records of your care generated by Karma TMS, whether created
                                by our staff,
                                physicians, or business associates. Your health information may include:
                            </p>
                            <div class="grid md:grid-cols-2 gap-4">
                                <ul class="space-y-2">
                                    <li class="flex items-start gap-3">
                                        <i data-lucide="check-circle" class="w-5 h-5 flex-shrink-0 mt-0.5"
                                            style="color: #572670;"></i>
                                        <span class="text-gray-600">Medical history and records</span>
                                    </li>
                                    <li class="flex items-start gap-3">
                                        <i data-lucide="check-circle" class="w-5 h-5 flex-shrink-0 mt-0.5"
                                            style="color: #572670;"></i>
                                        <span class="text-gray-600">Treatment plans and progress notes</span>
                                    </li>
                                    <li class="flex items-start gap-3">
                                        <i data-lucide="check-circle" class="w-5 h-5 flex-shrink-0 mt-0.5"
                                            style="color: #572670;"></i>
                                        <span class="text-gray-600">Laboratory and test results</span>
                                    </li>
                                </ul>
                                <ul class="space-y-2">
                                    <li class="flex items-start gap-3">
                                        <i data-lucide="check-circle" class="w-5 h-5 flex-shrink-0 mt-0.5"
                                            style="color: #572670;"></i>
                                        <span class="text-gray-600">Billing and insurance information</span>
                                    </li>
                                    <li class="flex items-start gap-3">
                                        <i data-lucide="check-circle" class="w-5 h-5 flex-shrink-0 mt-0.5"
                                            style="color: #572670;"></i>
                                        <span class="text-gray-600">Demographic and contact information</span>
                                    </li>
                                    <li class="flex items-start gap-3">
                                        <i data-lucide="check-circle" class="w-5 h-5 flex-shrink-0 mt-0.5"
                                            style="color: #572670;"></i>
                                        <span class="text-gray-600">Communication preferences</span>
                                    </li>
                                </ul>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- How We Use Information Section -->
    <section class="py-20" style="background: linear-gradient(to bottom right, #f8fafc, #faf5ff);">
        <div class="container mx-auto px-4">
            <div class="text-center mb-16">
                <h2 class="text-3xl lg:text-4xl font-bold text-gray-900 mb-6">
                    How We <span style="color: #572670;">Use Your Information</span>
                </h2>
                <p class="text-xl text-gray-600 max-w-2xl mx-auto">
                    We use and disclose your health information for the following primary purposes:
                </p>
            </div>

            <div class="grid md:grid-cols-3 gap-8 mb-12">
                <!-- Treatment -->
                <div class="bm-benefit-card p-6 hover:shadow-2xl transition-all">
                    <div class="flex items-center gap-4 mb-6">
                        <div class="w-12 h-12 rounded-xl flex items-center justify-center"
                            style="background: linear-gradient(to bottom right, #572670, #a855f7);">
                            <i data-lucide="users" class="w-6 h-6 text-white"></i>
                        </div>
                        <h3 class="text-xl font-bold text-gray-900">Treatment</h3>
                    </div>
                    <ul class="space-y-3">
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Coordinating your care among healthcare providers</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Consulting with specialists about your condition</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Sharing information with healthcare team members</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Emergency treatment situations</span>
                        </li>
                    </ul>
                </div>

                <!-- Payment -->
                <div class="bm-benefit-card p-6 hover:shadow-2xl transition-all">
                    <div class="flex items-center gap-4 mb-6">
                        <div class="w-12 h-12 rounded-xl flex items-center justify-center"
                            style="background: linear-gradient(to bottom right, #572670, #a855f7);">
                            <i data-lucide="scale" class="w-6 h-6 text-white"></i>
                        </div>
                        <h3 class="text-xl font-bold text-gray-900">Payment</h3>
                    </div>
                    <ul class="space-y-3">
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Processing insurance claims and authorizations</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Billing and collection activities</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Determining coverage and benefits</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Utilization review and quality assurance</span>
                        </li>
                    </ul>
                </div>

                <!-- Healthcare Operations -->
                <div class="bm-benefit-card p-6 hover:shadow-2xl transition-all">
                    <div class="flex items-center gap-4 mb-6">
                        <div class="w-12 h-12 rounded-xl flex items-center justify-center"
                            style="background: linear-gradient(to bottom right, #572670, #a855f7);">
                            <i data-lucide="shield" class="w-6 h-6 text-white"></i>
                        </div>
                        <h3 class="text-xl font-bold text-gray-900">Healthcare Operations</h3>
                    </div>
                    <ul class="space-y-3">
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Quality assessment and improvement activities</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Staff training and competency evaluation</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Business planning and development</span>
                        </li>
                        <li class="flex items-start gap-3">
                            <div class="w-2 h-2 rounded-full mt-2 flex-shrink-0" style="background-color: #572670;">
                            </div>
                            <span class="text-gray-600 text-sm">Compliance and regulatory oversight</span>
                        </li>
                    </ul>
                </div>
            </div>

            <!-- Special Situations -->
            <div class="max-w-4xl mx-auto">
                <div class="bm-benefit-card p-8">
                    <div class="flex items-center gap-4 mb-6">
                        <div class="w-12 h-12 rounded-xl flex items-center justify-center"
                            style="background: linear-gradient(to bottom right, #f97316, #ef4444);">
                            <i data-lucide="alert-circle" class="w-6 h-6 text-white"></i>
                        </div>
                        <h3 class="text-2xl font-bold text-gray-900">Special Situations</h3>
                    </div>
                    <p class="text-gray-600 mb-6">
                        We may also use or disclose your health information in the following special situations:
                    </p>
                    <div class="grid md:grid-cols-2 gap-6">
                        <div class="p-4 rounded-r-lg"
                            style="border-left: 4px solid #572670; background-color: #f9fafb;">
                            <h4 class="font-bold text-gray-900 mb-2">Required by Law</h4>
                            <p class="text-gray-600 text-sm">We may disclose health information when required by
                                federal, state, or local law.</p>
                        </div>
                        <div class="p-4 rounded-r-lg"
                            style="border-left: 4px solid #572670; background-color: #f9fafb;">
                            <h4 class="font-bold text-gray-900 mb-2">Public Health Activities</h4>
                            <p class="text-gray-600 text-sm">Reporting communicable diseases, adverse drug reactions, or
                                product recalls to public health authorities.</p>
                        </div>
                        <div class="p-4 rounded-r-lg"
                            style="border-left: 4px solid #572670; background-color: #f9fafb;">
                            <h4 class="font-bold text-gray-900 mb-2">Abuse or Neglect</h4>
                            <p class="text-gray-600 text-sm">Reporting suspected abuse, neglect, or domestic violence to
                                appropriate authorities as required by law.</p>
                        </div>
                        <div class="p-4 rounded-r-lg"
                            style="border-left: 4px solid #572670; background-color: #f9fafb;">
                            <h4 class="font-bold text-gray-900 mb-2">Legal Proceedings</h4>
                            <p class="text-gray-600 text-sm">Responding to court orders, subpoenas, or administrative
                                requests in legal proceedings.</p>
                        </div>
                        <div class="p-4 rounded-r-lg"
                            style="border-left: 4px solid #572670; background-color: #f9fafb;">
                            <h4 class="font-bold text-gray-900 mb-2">Law Enforcement</h4>
                            <p class="text-gray-600 text-sm">Limited disclosures to law enforcement for specific
                                purposes as permitted by law.</p>
                        </div>
                        <div class="p-4 rounded-r-lg"
                            style="border-left: 4px solid #572670; background-color: #f9fafb;">
                            <h4 class="font-bold text-gray-900 mb-2">Serious Threats</h4>
                            <p class="text-gray-600 text-sm">Preventing or lessening a serious and imminent threat to
                                health or safety.</p>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Your Rights Section -->
    <section class="py-20 bg-white">
        <div class="container mx-auto px-4">
            <div class="text-center mb-16">
                <h2 class="text-3xl lg:text-4xl font-bold text-gray-900 mb-6">
                    Your <span style="color: #572670;">Privacy Rights</span>
                </h2>
                <p class="text-xl text-gray-600 max-w-3xl mx-auto">
                    Under HIPAA, you have specific rights regarding your health information.
                    These rights are designed to give you control over your personal health data.
                </p>
            </div>

            <div class="space-y-8">
                <!-- Right 1: Access -->
                <div class="bm-benefit-card p-8 hover:shadow-2xl transition-all">
                    <div class="flex items-start gap-6">
                        <div class="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0"
                            style="background: linear-gradient(to bottom right, #572670, #a855f7);">
                            <i data-lucide="eye" class="w-6 h-6 text-white"></i>
                        </div>
                        <div class="flex-1">
                            <h3 class="text-2xl font-bold text-gray-900 mb-3">Access Your Health Information</h3>
                            <p class="text-gray-600 mb-6">You have the right to inspect and obtain copies of your health
                                records, with some limited exceptions.</p>
                            <div class="grid md:grid-cols-2 gap-4">
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Request copies of medical records, billing
                                        records, and other health information</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">We may charge a reasonable fee for copying and
                                        mailing costs</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">We will respond to your request within 30
                                        days</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">In certain circumstances, we may deny access but
                                        will provide written explanation</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Right 2: Amendments -->
                <div class="bm-benefit-card p-8 hover:shadow-2xl transition-all">
                    <div class="flex items-start gap-6">
                        <div class="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0"
                            style="background: linear-gradient(to bottom right, #572670, #a855f7);">
                            <i data-lucide="file-text" class="w-6 h-6 text-white"></i>
                        </div>
                        <div class="flex-1">
                            <h3 class="text-2xl font-bold text-gray-900 mb-3">Request Amendments</h3>
                            <p class="text-gray-600 mb-6">You can ask us to amend health information that you believe is
                                incorrect or incomplete.</p>
                            <div class="grid md:grid-cols-2 gap-4">
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Submit amendment requests in writing with
                                        supporting documentation</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">We will respond within 60 days of receiving your
                                        request</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">If denied, you have the right to file a
                                        statement of disagreement</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Approved amendments will be shared with relevant
                                        parties</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Right 3: Restrictions -->
                <div class="bm-benefit-card p-8 hover:shadow-2xl transition-all">
                    <div class="flex items-start gap-6">
                        <div class="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0"
                            style="background: linear-gradient(to bottom right, #572670, #a855f7);">
                            <i data-lucide="lock" class="w-6 h-6 text-white"></i>
                        </div>
                        <div class="flex-1">
                            <h3 class="text-2xl font-bold text-gray-900 mb-3">Request Restrictions</h3>
                            <p class="text-gray-600 mb-6">You may request limits on how we use or disclose your health
                                information.</p>
                            <div class="grid md:grid-cols-2 gap-4">
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Request restrictions on disclosures to family
                                        members or friends</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Limit information shared for treatment, payment,
                                        or operations</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">We are not required to agree to all
                                        restrictions</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Any agreed restrictions will be documented and
                                        followed</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Right 4: Alternative Communications -->
                <div class="bm-benefit-card p-8 hover:shadow-2xl transition-all">
                    <div class="flex items-start gap-6">
                        <div class="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0"
                            style="background: linear-gradient(to bottom right, #572670, #a855f7);">
                            <i data-lucide="mail" class="w-6 h-6 text-white"></i>
                        </div>
                        <div class="flex-1">
                            <h3 class="text-2xl font-bold text-gray-900 mb-3">Alternative Communications</h3>
                            <p class="text-gray-600 mb-6">You can request that we contact you in a specific way or at a
                                certain location.</p>
                            <div class="grid md:grid-cols-2 gap-4">
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Request communications at alternative addresses
                                        or phone numbers</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Specify preferred method of contact (phone,
                                        email, mail)</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">We will accommodate reasonable requests</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">May require information about how payment will
                                        be handled</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Right 5: Accounting -->
                <div class="bm-benefit-card p-8 hover:shadow-2xl transition-all">
                    <div class="flex items-start gap-6">
                        <div class="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0"
                            style="background: linear-gradient(to bottom right, #572670, #a855f7);">
                            <i data-lucide="book-open" class="w-6 h-6 text-white"></i>
                        </div>
                        <div class="flex-1">
                            <h3 class="text-2xl font-bold text-gray-900 mb-3">Accounting of Disclosures</h3>
                            <p class="text-gray-600 mb-6">You can receive a list of certain disclosures we have made of
                                your health information.</p>
                            <div class="grid md:grid-cols-2 gap-4">
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Covers disclosures made for purposes other than
                                        treatment, payment, or operations</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Includes dates, recipients, and purposes of
                                        disclosures</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">First accounting in any 12-month period is
                                        free</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Additional requests may incur reasonable
                                        fees</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Right 6: Complaints -->
                <div class="bm-benefit-card p-8 hover:shadow-2xl transition-all">
                    <div class="flex items-start gap-6">
                        <div class="w-12 h-12 rounded-xl flex items-center justify-center flex-shrink-0"
                            style="background: linear-gradient(to bottom right, #572670, #a855f7);">
                            <i data-lucide="alert-circle" class="w-6 h-6 text-white"></i>
                        </div>
                        <div class="flex-1">
                            <h3 class="text-2xl font-bold text-gray-900 mb-3">File Complaints</h3>
                            <p class="text-gray-600 mb-6">You have the right to file complaints about our privacy
                                practices.</p>
                            <div class="grid md:grid-cols-2 gap-4">
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">File complaints with us or with the Secretary of
                                        Health and Human Services</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">We will not retaliate against you for filing a
                                        complaint</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">Complaints should be submitted in writing when
                                        possible</span>
                                </div>
                                <div class="flex items-start gap-3">
                                    <i data-lucide="info" class="w-4 h-4 flex-shrink-0 mt-1"
                                        style="color: #572670;"></i>
                                    <span class="text-gray-600 text-sm">We will investigate and respond to all
                                        complaints promptly</span>
                                </div>
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- Contact Information Section -->
    <section class="py-20" style="background: linear-gradient(to bottom right, #f8fafc, #faf5ff);">
        <div class="container mx-auto px-4">
            <div class="max-w-4xl mx-auto">
                <div class="text-center mb-12">
                    <h2 class="text-3xl lg:text-4xl font-bold text-gray-900 mb-6">
                        <span style="color: #572670;">Contact</span> Information
                    </h2>
                </div>

                <!-- Contact Cards -->
                <div class="grid md:grid-cols-2 gap-8 mb-12">
                    <!-- Privacy Officer -->
                    <div class="bm-benefit-card p-8" style="border-left: 4px solid #572670;">
                        <div class="flex items-center gap-4 mb-6">
                            <i data-lucide="user-check" class="w-8 h-8" style="color: #572670;"></i>
                            <h3 class="text-xl font-bold text-gray-900">Privacy Officer</h3>
                        </div>
                        <div class="space-y-3 text-gray-600">
                            <p><strong>Dr. Sarah Mitchell, Medical Director</strong></p>
                            <p>Karma TMS</p>
                            <p>123 Medical Plaza<br>Palm Springs, CA 92262</p>
                            <div class="flex items-center gap-2 pt-2">
                                <i data-lucide="phone" class="w-4 h-4"></i>
                                <span>760-760-5675</span>
                            </div>
                            <div class="flex items-center gap-2">
                                <i data-lucide="mail" class="w-4 h-4"></i>
                                <span>privacy@karmatms.com</span>
                            </div>
                        </div>
                    </div>

                    <!-- Federal Complaint -->
                    <div class="bm-benefit-card p-8" style="border-left: 4px solid #a855f7;">
                        <div class="flex items-center gap-4 mb-6">
                            <i data-lucide="shield" class="w-8 h-8" style="color: #a855f7;"></i>
                            <h3 class="text-xl font-bold text-gray-900">Federal Complaint Option</h3>
                        </div>
                        <div class="space-y-3 text-gray-600">
                            <p><strong>U.S. Department of Health & Human Services</strong></p>
                            <p>Office for Civil Rights</p>
                            <p>Region IX Office<br>90 7th Street, Suite 4-100<br>San Francisco, CA 94103</p>
                            <div class="flex items-center gap-2 pt-2">
                                <i data-lucide="phone" class="w-4 h-4"></i>
                                <span>(415) 437-8310</span>
                            </div>
                            <div class="flex items-center gap-2">
                                <i data-lucide="mail" class="w-4 h-4"></i>
                                <span>OCRComplaint@hhs.gov</span>
                            </div>
                        </div>
                    </div>
                </div>

                <!-- Questions Section -->
                <div class="text-center p-8 rounded-2xl"
                    style="background: linear-gradient(to bottom right, rgba(87, 38, 112, 0.05), rgba(168, 85, 247, 0.1));">
                    <h3 class="text-2xl font-bold text-gray-900 mb-4">Questions About Your Privacy Rights?</h3>
                    <p class="text-gray-600 mb-6">
                        If you have questions about this notice or your privacy rights, or if you believe
                        your privacy rights have been violated, please contact us immediately.
                    </p>
                    <div class="flex flex-row flex-wrap gap-4 justify-center">
                        <a href="tel:7607605675" class="bm-hero-btn" style="background-color: #572670;">
                            <i data-lucide="phone" class="w-4 h-4 mr-2"></i>
                            Call: 760-760-5675
                        </a>
                        <a href="mailto:privacy@karmatms.com" class="bm-outline-btn"
                            style="border-color: #572670; color: #572670;">
                            <i data-lucide="mail" class="w-4 h-4 mr-2"></i>
                            privacy@karmatms.com
                        </a>

                    </div>
                </div>

                <!-- Related Documents -->
                <div class="mt-12 text-center">
                    <h3 class="text-xl font-bold text-gray-900 mb-4">Related Privacy Documents</h3>
                    <div class="flex flex-wrap justify-center gap-4">
                        <a href="privacy.php" class="bm-outline-btn"
                            style="border-color: #572670; color: #572670; text-decoration: none;">
                            Privacy Policy
                        </a>

                        <a href="contact-us.php" class="bm-outline-btn"
                            style="border-color: #572670; color: #572670; text-decoration: none;">
                            Contact Us
                        </a>
                    </div>
                </div>

                <!-- Acknowledgment -->
                <div class="mt-12 p-6 bg-gray-50 rounded-xl">
                    <p class="text-sm text-gray-600 text-center">
                        <strong>Acknowledgment:</strong> This Notice of Privacy Practices describes how we may use
                        and disclose your protected health information and how you can access this information.
                        We are required by law to maintain the privacy of your health information and to provide
                        you with notice of our legal duties and privacy practices.
                    </p>
                </div>
            </div>
        </div>
    </section>

    <?php include 'includes/footer.php'; ?>

    <script>
        document.addEventListener('DOMContentLoaded', () => {
            lucide.createIcons();
        });
    </script>
</body>

</html>

